BEGIN;


CREATE TABLE IF NOT EXISTS public.booking
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_time timestamp without time zone NOT NULL,
    start_time timestamp without time zone NOT NULL,
    customer_id bigint,
    service_id bigint,
    CONSTRAINT booking_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    CONSTRAINT service_pkey PRIMARY KEY (id),
    CONSTRAINT uk_adgojnrwwx9c3y3qa2q08uuqp UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.timeslot
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    available boolean NOT NULL,
    end_time timestamp without time zone NOT NULL,
    start_time timestamp without time zone NOT NULL,
    service_id bigint,
    CONSTRAINT timeslot_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT fkcebnlefwi9r13txu8btclnmsu FOREIGN KEY (service_id)
    REFERENCES public.service (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT fklnnelfsha11xmo2ndjq66fvro FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.timeslot
    ADD CONSTRAINT fkok6fgeqmep7ykwcwe3i8cuyhg FOREIGN KEY (service_id)
    REFERENCES public.service (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;